routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/', 'HomeController@index')->name('home1');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('user/logout', 'HomeController@logout')->name('user.logout');
Route::group([ 'middleware' => ['auth']] ,function () {
    Route::group(['middleware' => ['IsAdmin']] ,function () {
        Route::get('/create/', 'StaffController@create')->name('staff.create');
        Route::post('/store/', 'StaffController@store')->name('staff.store');
        Route::get('/showAll/', 'StaffController@showAllStaff')->name('staff.showAll');
        Route::get('/edit/{id}', 'StaffController@edit')->name('staff.edit');
        Route::post('/update/', 'StaffController@update')->name('staff.update');
        Route::get('/delete/{id}', 'StaffController@destroy')->name('staff.delete');
    });
    Route::group(['prefix' => 'client', 'middleware' => ['IsAdmin']], function () {
        Route::post('/caseManager/', 'StaffController@caseManager')->name('staff.caseManager');
        Route::post('/UnmarkCaseManager/', 'StaffController@unMarkaseManager')->name('staff.unMarkCaseManager');
    });
    Route::get('/ShowAll/', 'ClientController@showAllClient')->name('client.showAll');
    Route::get('/staff_client/', 'StaffController@staffClient')->name('staff.client');
    Route::get('/all_forms/{id}', 'HomeController@allForms')->name('all.forms');
    Route::group(['prefix' =>'client' ] ,function () {
        Route::get('/Show/', 'ClientController@show')->name('client.show')->middleware('IsClient');
        Route::get('/delete/{id}', 'ClientController@destroy')->name('client.details');
        Route::get('/edit/{id}', 'ClientController@edit')->name('client.edit');
        Route::post('/update/', 'ClientController@update')->name('client.update');
        Route::get('/delete/{id}', 'ClientController@destroy')->name('client.delete');
        Route::get('/details/{id}', 'ClientController@details')->name('client.details');
        Route::get('/profile/', 'ClientController@clientProfile')->name('client.profile');
});
    Route::group(['prefix' => 'staff', 'middleware' => ['IsStaff']], function () {
    Route::get('/show/', 'StaffController@show')->name('staff.show');
    Route::get('/view/', 'StaffController@staffDetails')->name('staff.view');
});
Route::prefix('disease')->group(function () {
    Route::get('/show/', 'DiseaseController@show')->name('disease.show');
    Route::get('/create/', 'DiseaseController@create')->name('disease.create');
    Route::post('/store/', 'DiseaseController@store')->name('disease.store');
    Route::get('/edit/{id}', 'DiseaseController@edit')->name('disease.edit');
    Route::post('/update/', 'DiseaseController@update')->name('disease.update');
    Route::get('/delete/{id}', 'DiseaseController@destroy')->name('disease.delete');
});
Route::prefix('cases')->group(function () {
    Route::get('/clientcases/{id}', 'ClientCaseController@ShowClientCases')->name('cases.clientcases');
    Route::get('/allcases/', 'ClientCaseController@ShowAllCases')->name('cases.allcases');
    Route::get('/create/{id}', 'ClientCaseController@create')->name('cases.create');
    Route::post('/store/', 'ClientCaseController@store')->name('cases.store');
    Route::get('/edit/{id}', 'ClientCaseController@edit')->name('cases.edit');
    Route::post('/update/', 'ClientCaseController@update')->name('cases.update');
    Route::get('/delete/{id}', 'ClientCaseController@destroy')->name('cases.delete');
    Route::get('/details/{id}', 'ClientCaseController@details')->name('cases.details');
});
    Route::prefix('casesassignmemt')->group(function () {
    Route::get('/show/{id}', 'CasesAssignmentController@show')->name('assignment.show');
    Route::post('/assign-casemanager/', 'CasesAssignmentController@store')->name('assignment.store');
    Route::get('/edit/{id}', 'CasesAssignmentController@edit')->name('assignment.edit');
    Route::get('/update/', 'CasesAssignmentController@update')->name('assignment.update');
    Route::get('/client-And-Managers/', 'CasesAssignmentController@viewAll')->name('assigned.managers');
    Route::get('/delete/{id}', 'CasesAssignmentController@destroy')->name('assignment.destroy');
});
    Route::prefix('provider')->group(function () {
    Route::get('/show/', 'ProviderController@show')->name('provider.show');
    Route::get('/showAll/', 'ProviderController@showAll')->name('provider.showAll');
    Route::get('/create', 'ProviderController@create')->name('provider.create');
    Route::post('/store', 'ProviderController@store')->name('provider.store');
    Route::get('/edit/{id}', 'ProviderController@edit')->name('provider.edit');
    Route::post('/update/{id}', 'ProviderController@update')->name('provider.update');
    Route::get('/delete/{id}', 'ProviderController@destroy')->name('provider.delete');
    });

    Route::group(['middleware' => ['IsAdmin']] ,function () {
    Route::resource('casemanager', 'CaseManagersController');
    });

    Route::get('/my_client_forms/{id}', 'AppendixD5Controller@myClientForms')->name('my.client.forms');
    Route::get('/create_form/{id}', 'AppendixD5Controller@createForm')->name('AppendixD5.create_form');
    Route::resource('AppendixD5', 'AppendixD5Controller');



    Route::get('/ClientChangeForm/{id}', 'ClientChangeFormController@myClientForms')->name('client.change.form');
    Route::get('/ClientChangeForm_create/{id}', 'ClientChangeFormController@createForm')->name('ClientChangeForm.create_form');
    Route::get('ClientChangeForm_show/{id}', 'ClientChangeFormController@show')->name('ClientChangeForm_show');
    Route::get('ClientChangeForm_edit/{id}', 'ClientChangeFormController@editForm')->name('ClientChangeForm_edit');




    Route::get('/appendixkData/{id}', 'AppendixK1Controller@myClientForms')->name('Appendixmy.client.forms');
    Route::get('/create_appendixk1/{id}', 'AppendixK1Controller@createForm')->name('AppendixK1.create_form');
    Route::resource('AppendixK1', 'AppendixK1Controller');
    Route::resource('ClientChangeForm', 'ClientChangeFormController');



    Route::get('/monthlyVisitReport/{id}', 'MonthlyVisitFormController@myClientForms')->name('monthlyVisitReport.forms');
    Route::get('/createmonthlyVisitReport/{id}', 'MonthlyVisitFormController@createForm')->name('monthlyVisitReport.create_form');
    Route::resource('monthlyVisitReport', 'MonthlyVisitFormController');
    Route::get('monthlyVisitReport_show/{id}', 'MonthlyVisitFormController@show')->name('monthlyVisitReport_show');
    Route::get('monthlyVisitReport_edit/{id}', 'MonthlyVisitFormController@editForm')->name('monthlyVisitReport_edit');
    // Route::get('temp', 'TemperatureController@index');



    Route::get('/monthlyContactReport/{id}', 'MonthlyContactFormController@myClientForms')->name('monthlyContactReport.forms');
    Route::get('/createmonthlyContactReport/{id}', 'MonthlyContactFormController@createForm')->name('monthlyContactReport.create_form');
    Route::resource('monthlyContactReport', 'MonthlyContactFormController');
    Route::get('monthlyContactReport_show/{id}', 'MonthlyContactFormController@show')->name('monthlyContactReport_show');
    Route::get('monthlyContactReport_edit/{id}', 'MonthlyContactFormController@editForm')->name('monthlyContactReport_edit');

    Route::get('/followup/{id}', 'FollowupController@myClientForms')->name('followup.forms');
    Route::get('/createfollowup/{id}', 'FollowupController@createForm')->name('followup.create_form');
    Route::resource('followup', 'FollowupController');
    Route::get('followup_show/{id}', 'FollowupController@show')->name('followup_show');
    Route::get('followup_edit/{id}', 'FollowupController@editForm')->name('followup_edit');

    Route::get('/careform/{id}', 'CareformController@myClientForms')->name('careform.forms');
    Route::get('/createcareform/{id}', 'CareformController@createForm')->name('careform.create_form');
    Route::resource('careform', 'CareformController');
    Route::get('careform_show/{id}', 'CareformController@show')->name('careform_show');
    Route::get('careform_edit/{id}', 'CareformController@editForm')->name('careform_edit');
    Route::get('careform_forms/{id}', 'CareformController@careform_forms')->name('careform_forms');

// Care Form --- Form 1 part -------------- Start
    Route::get('careform_form1Update/{id}', 'CareformForm1Controller@careform_form1Update')->name('careform_form1Update');
    Route::get('careform_form1index/{id}', 'CareformForm1Controller@index')->name('careform_form1index');
// Care Form --- Form 1 part -------------- Over

// Care Form --- Form 2 part -------------- Start
    Route::get('careform_form2index/{id}', 'CareformForm2Controller@index')->name('careform_form2index');
    Route::get('careform_form2Update/{id}', 'CareformForm2Controller@careform_form2Update')->name('careform_form2Update');
// Care Form --- Form 2 part -------------- Over

    // Care Form --- Form 3 part -------------- Start
    Route::get('careform_form3index/{id}', 'CareformForm3Controller@index')->name('careform_form3index');
    Route::get('careform_form3Update/{id}', 'CareformForm3Controller@careform_form3Update')->name('careform_form3Update');
    // Care Form --- Form 3 part -------------- Over

// Care Form --- Form 4 part -------------- Start
Route::get('careform_form4index/{id}', 'CareformForm4Controller@index')->name('careform_form4index');
Route::get('careform_form4Update/{id}', 'CareformForm4Controller@careform_form4Update')->name('careform_form4Update');
// Care Form --- Form 4 part -------------- Over

// Care Form --- Form 5 part -------------- Start

app/Http/Controllers/ClientChangeFormController.php
<?php

namespace App\Http\Controllers;

use App\ClientChangeForm;
use Illuminate\Http\Request;

class ClientChangeFormController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id)
    {
        $clientId = $id;
        return view('Forms.ClientChangeForm.index',$clientId);
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Forms.ClientChangeForm.create');
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->merge([
            'change_type' => implode(',', (array) $request->get('change_type'))
        ]);

        $data = $request->all();

        $isCreated = ClientChangeForm::create($data);
        return redirect()->route('client.change.form',$request->client_id);

        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ClientChangeForm  $clientChangeForm
     * @return \Illuminate\Http\Response
     */
    public function show(ClientChangeForm $clientChangeForm ,$id)
    {
        // dd('Show by Id');
        $form = ClientChangeForm::find($id);
        return view('Forms.ClientChangeForm.show',compact('form'));
    }
    public function editForm(ClientChangeForm $clientChangeForm ,$id)
    {
        $clientId = $id;
        // dd('Show by Id');
        $form = ClientChangeForm::find($id);
        return view('Forms.ClientChangeForm.edit',compact('form','clientId'));
    }

    public function myClientForms($id)
    {
        $data['clientId'] = $id;
        $data['forms'] = ClientChangeForm::where('client_id', $id)->get();
        return view('Forms.ClientChangeForm.index',$data);
    }
    public function createForm($id)
    {
        $clientId = $id;
        return view('Forms.ClientChangeForm.create',compact('clientId'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ClientChangeForm  $clientChangeForm
     * @return \Illuminate\Http\Response
     */
    public function edit(ClientChangeForm $clientChangeForm)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ClientChangeForm  $clientChangeForm
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ClientChangeForm $clientChangeForm,$id)
    {
        $request->merge([
            'change_type' => implode(',', (array) $request->get('change_type'))
        ]);
        $data = $request->all();
        $isUpdated = ClientChangeForm::find($id)->update($data);

        return redirect()->route('client.change.form',$request->client_id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ClientChangeForm  $clientChangeForm
     * @return \Illuminate\Http\Response
     */
    public function destroy(ClientChangeForm $clientChangeForm,$id)
    {

        $isDeleted =  ClientChangeForm::where('id', $id)->delete();
        if($isDeleted)
        {
            return back();
        }
    }
}

resources/views/Forms/ClientChangeForm/create.blade.php
@extends('layouts.masterlayout')

@section('content')

    <!-- All CSS -->
    {{--    <link href="{{asset('css/all.css')}}" rel="stylesheet">--}}
    {{--    <!-- slicknav CSS -->--}}
    {{--    <link href="{{asset('css/slicknav.css')}}" rel="stylesheet">--}}
    <!-- Style CSS -->
    <link href="{{asset('css/custom.css')}}" rel="stylesheet">
    <!-- responsive css -->
    <link href="{{asset('css/responsive.css')}}" rel="stylesheet">
    <!-- Google Fonts CSS -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">

    <body class="responsive">
        <form method="POST" action="{{route('ClientChangeForm.store')}}">
            @csrf
            @method('post')

            <input type="hidden" name="client_id" value="{{$clientId}}">
        <div class="allPadding">
          <div class="topSecform">
            <div class="container">
              <div class="formHead">
                <div class="row">
                  <div class="col-md-8 col-sm-8 col-xs-12 centerCol">
                    <h2>Client Change Form</h2>
                  </div>
                </div>
              </div>
              <div class="formTable ">
                <div class="row flexRow">
                  <div class="col-md-2 col-sm-2 col-xs-12 noPadding">
                    <div class="heading">
                      <h4>Member Name:</h4>
                    </div>
                  </div>
                  <div class="col-md-4 col-sm-4 col-xs-12 noPadding">
                    <div class="putData">
                      <input type="text" name="member_name">
                    </div>
                  </div>
                  <div class="col-md-3 col-sm-3 col-xs-12 noPadding">
                    <div class="heading">
                      <h4>Date of Change:</h4>
                    </div>
                  </div>
                  <div class="col-md-3 col-sm-3 col-xs-12 noPadding">
                    <div class="putData">
                      <input type="text" name="date_of_change">
                    </div>
                  </div>
                </div>
                <div class="row flexRow">
                  <div class="col-md-3 col-sm-3 col-xs-12 noPadding">
                    <div class="heading">
                      <h4>Change Type:</h4>
                    </div>
                  </div>
                  <div class="col-md-9 col-sm-9 col-xs-12 noPadding">
                    <ul class="list-inline checkboxes">
                      <li>
                        <input type="checkbox" name="change_type[]" value="1">
                        <label for=""> Case Manager</label>
                      </li>
                      <li>
                        <input type="checkbox" name="change_type[]" value="2">
                        <label for=""> Hospitalization</label>
                      </li>
                      <li>
                        <input type="checkbox" name="change_type[]" value="3">
                        <label for="">Personal Support Provider</label>
                      </li>
                      <li>
                        <input type="checkbox" name="change_type[]" value="4">
                        <label for="">Respite</label>
                      </li>
                    </ul>
                  </div>
                </div>
                <div class="row flexRow">
                  <div class="col-md-6 col-sm-6 col-xs-12 noPadding">
                    <div class="heading">
                      <h4>Name of new Case Manager/Personal Support Provider:</h4>
                    </div>
                  </div>
                  <div class="col-md-6 col-sm-6 col-xs-12 noPadding">
                    <div class="putData">
                      <input type="text" name="name_new_case_manager">
                    </div>
                  </div>
                </div>
                <div class="row flexRow">
                  <div class="col-md-2 col-sm-2 col-xs-12 noPadding">
                    <div class="heading">
                      <h4>Respite:</h4>
                    </div>
                  </div>
                  <div class="col-md-2 col-sm-2 col-xs-12 noPadding">
                    <div class="heading">
                      <h4>Approved Hours:</h4>
                    </div>
                  </div>
                  <div class="col-md-2 col-sm-2 col-xs-12 noPadding">
                    <div class="putData">
                      <input type="text" name="approved_hours">
                    </div>
                  </div>
                  <div class="col-md-3 col-sm-3 col-xs-12 noPadding">
                    <div class="heading">
                      <h4>Remaining Hours:</h4>
                    </div>
                  </div>
                  <div class="col-md-1 col-sm-1 col-xs-12 noPadding">
                    <div class="putData">
                      <input type="text" name="remaining_hours">
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="additionSec">
            <div class="container">
              <h4>Additional Notes/Documentation:</h4>
              <textarea rows="10" name="additionals_notes_documentation"></textarea>
            </div>
          </div>
          <div class="signSec">
            <div class="container">
              <div class="row">
                <div class="col-md-3 col-sm-3 col-xs-12">
                  <div class="heading">
                    <h4>CASE MANAGER SIGNATURE:</h4>
                  </div>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-12">
                  <div class="putData">
                    <input type="text" name="case_manager_signature">
                  </div>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-12">
                </div>
                <div class="col-md-1 col-sm-1 col-xs-12">
                  <div class="heading">
                    <h4>DATE:</h4>
                  </div>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-12">
                  <div class="putData">
                    <input type="text" name="case_manager_date">
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="signSec">
            <div class="container">
              <div class="row">
                <div class="col-md-3 col-sm-3 col-xs-12">
                  <div class="heading">
                    <h4>OWNER SIGNATURE:</h4>
                  </div>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-12">
                  <div class="putData">
                    <input type="text" name="owner_signature">
                  </div>
                </div>
                <div class="col-md-2 col-sm-2 col-xs-12">
                </div>
                <div class="col-md-1 col-sm-1 col-xs-12">
                  <div class="heading">
                    <h4>DATE:</h4>
                  </div>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-12">
                  <div class="putData">
                    <input type="text" name="owner_date">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <center> <input type="submit" value="Save" name="btnSubmit" class="btn btn-success"></center>
        </form>
      </body>

    <!-- All JS -->
    <script src="{{asset('js/all.js')}}"></script>
    <!-- jquery.slicknav JS -->
    <script src="{{asset('js/jquery.slicknav.js')}}"></script>
    <!-- Custom JS -->
    <script src="{{asset('js/custom.js')}}"></script>

@endsection

resources/views/Forms/ClientChangeForm/index.blade.php
@extends('layouts.masterlayout')

@section('content')
@php
$roleuser=Illuminate\Support\Facades\Auth::user()->roles;
@endphp
@if($roleuser=="staff")
<a href="{{route('ClientChangeForm.create_form',$clientId)}}" class="btn btn-success fa-pull-right" style="margin-right: 20px;">Create Form</a>
@endif
<br>
    <br>

    <section id="widget-grid" class="" style="border-top:2px solid #CCC; margin-left: 10px; margin-right: 10px">
        <!-- row -->
        <div class="row">
            <!-- NEW WIDGET START -->
            <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">

                    <!-- widget div-->
                    <div>
                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->
                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">
                            <div class="widget-body-toolbar" style="overflow-x:auto;">
                            </div >
                            <table id="datatable_tabletools" class="table table-striped table-hover table-bordered">
                                <thead>
                                <tr>
                                    <th nowrap><center>S#</center></th>
                                    <th nowrap><center>Member’s Name:</center></th>
                                    <th nowrap><center>Date Of Change</center></th>
                                    <th nowrap><center>Approved Hours</center></th>
                                    <th nowrap><center>Action</center></th>
                                </tr>
                                </thead>
                                <tbody>

                                @foreach($forms as $form)
                                    <tr>
                                        <td nowrap>{{$loop->iteration}}</td>
                                        <td nowrap>{{$form->member_name}}</td>
                                        <td nowrap>{{$form->date_of_change}}</td>
                                        <td nowrap>{{$form->approved_hours}}</td>

                                        <td nowrap> <center>
                                                @if(isset($form->is_manager) && $form->is_manager == 0)
                                                    <form method="POST" action="{{ route('staff.caseManager') }}">
                                                        @csrf
                                                        <input type="hidden" name="staffId" value="{{ $form->id }}">
                                                        <input type="submit" value="Mark Case Manager">
                                                    </form>
                                                @endif

                                                <a href="{{ route('ClientChangeForm_show', [$form->id]) }}" class="btn btn-sm btn-primary"  title="View" >
                                                    <i class="fa fa-eye" aria-hidden="true"></i>
                                                </a>
                                                @if($roleuser=="staff")
                                                <a href="{{ route('ClientChangeForm_edit', [$form->id]) }}" class="btn btn-sm btn-primary"  title="View" >
                                                    <i class="fa fa-edit" aria-hidden="true"></i>
                                                </a>
                                                {{--
                                                <a href="{{route('ClientChangeForm.edit',$form->id)}}" class="btn btn-sm btn-primary"  title="Edit">
                                                    <i class="fa fa-edit" aria-hidden="true"></i>
                                                </a> --}}
                                                    <form method="POST" action="{{route('ClientChangeForm.destroy',$form->id)}}">
                                                        @csrf
                                                        @method('delete')
                                                        <input type="submit" class="btn btn-sm btn-danger" value="Delete">
                                                    </form >
                                                    @endif
{{--                                                <a href="{{route('AppendixD5.destroy',$form->id)}}" class="btn btn-sm btn-primary"  title="Delete"  >--}}
{{--                                                    <i class="fa fa-trash" aria-hidden="true"></i>--}}
{{--                                                </a>--}}
                                            </center>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>

                                </tfoot>
                            </table>
                        </div>
                        <!-- end widget content -->
                    </div>
                    <!-- end widget div -->
                </div>
                <!-- end widget -->
            </article>
        </div>
    </section>

@endsection


<script>
    $('#datatable_tabletools').DataTable({
        dom: "<'dt-top-row'lf>" + "B" +"<'row'<'col-sm-12'tr>>" + "<'dt-row dt-bottom-row'<'col-sm-5'i><'col-sm-7 text-right'p>>",
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ],
        initComplete : function(oSettings, json) {
            $(this).closest('#dt_table_tools_wrapper').find('.dt-button').addClass('table_tools_group').children('button.dt-button').each(function() {
                $(this).addClass('btn-sm btn-default');
            });
        },
        "language": {
            "search": "Search: ",
            "searchPlaceholder": "Search records"
        },
        "pageLength": 50,
        "bDestroy": true,

        "order": []
    });
    /* END TABLE TOOLS */

    function ReportError(res)
    {
    }// Filter placeholder dataTable
    $(".dataTables_filter .input-group input").attr("placeholder", "Search records");

</script>